### ISSUE TITLE
피드백 받은 내용 (2022.10.17- 김용빈 매니저님)

### ISSUE THREAD

**Issue by kidonge** [HangHae99-9-week05-9/Spring_Project#7]
대댓글 그냥 Comment 엔티티 하나로 할 수 있지 않을까???

Exception을 중복 줄이고 관리 -> enum??(김동현 생각)

생성자 말고 빌더 사용하는 이유,  빌더 반복 줄이기???

getpost도 getpostlist와 중복되는 부분이 많다?? 어떻게 중복을 줄일지 

메소드 이름을 통일시키도록 해보자, 사람마다 메소드 이름 짓는 방식 다름

findAllby 이런거 할 떄 리스트로 받아오는데 만약 데이터가 완전 많으면 -> sql??로 댓글이 없는걸 찾기( jpql)

getAllComments는 userDetails를 받고있지만 userDetails의 내용 전부를 쓰고있지 않는다???? , 유저디테일 전부받지 말기??????

 만약 UserDetailsImpl을 사용하지 않는 곳에서 getAllPost를 못쓰는데(getAllPost에 매개변수가 UserDetailsImpl이 있으니) 범용성 넓게 사용하기 위해 어떻게 해야할까??? -> 매개변수로 UserDetailsImpl을 받지말고 매개변수로 멤버를 받고 바디 안에 UserDetail(멤버)같이 쓸 방법이 없을까????(정확하지 않음?)

getUserPost 부분에서 userDetail이 null인지 확인할 수 있게

유저가 작성한 글 조회하는 부분을 위해 UserDetailsImpl(?)에 onetomany 추가해보기 -> userDetails.getMember().getId() 간단하게 바꿀수 있을지도??

데이터를 주고받을 때 레이어드 아키텍쳐 준수???? ->  테스트하기 편하다??

**Comment by Puri12** [comment]
## Q
> getAllComments는 userDetails를 받고있지만 userDetails의 내용 전부를 쓰고있지 않는다???? , 유저디테일 전부받지 말기??????



# Solution
UserDetailsImpl.java

```Java
  public Long getId() {
    return member.getId();
  }
```
추가하여 Id 리턴해주면 될 것 같습니다.
